import Head from 'next/head';
import Header from '../components/Layout/Header';
import Sidebar from '../components/Layout/Sidebar';
import Category from '../components/Layout/Dropdowns/Category';
import Price from '../components/Layout/Dropdowns/Price';
import Search from '../components/Layout/Dropdowns/Search';
import Product from '../components/Product/Product';

const Products = () => {
	return (
		<>
			<Head>
				<title>PickBazar</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<div
				style={{height: 'calc(100vh - 92px)'}}
				className='flex items-center w-full'>
				<Sidebar />
				<div
					style={{width: 'calc(100% - 270px)'}}
					className='h-full flex bg-[#f7f7f7]'>
					<div className='py-[45px] px-[30px] h-auto w-full overflow-y-auto'>
						<div className='px-[16px]'>
							<div className='last:mb-0 box-border flex flex-initial flex-row flex-wrap mx-[-8px]'>
								<div className='col-lg'>
									<header
										className='p-[40px] flex flex-wrap flex-initial bg-white flex-row justify-between items-center'
										style={{marginBottom: '15px'}}>
										<div className='col-sm  box-border px-[8px]'>
											<h3 className='mr-[80px] text-[18px] leading-6 font-bold text-[#161f6a]'>
												Products
											</h3>
										</div>
										<div className='col-start-1 box-border px-[8px]'>
											<div className='last:mb-0 box-border flex flex-initial flex-row flex-wrap mx-[-8px]'>
												<Category />
												<Price />
												<Search />
											</div>
										</div>
									</header>
									<div className='box-border flex flex-initial flex-row flex-wrap mx-[-8px]'>
										<div className='col-lg box-border'>
											<Product />
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</>
	);
};

export default Products;


