import Head from 'next/head';
import Header from '../components/Layout/Header';
import Sidebar from '../components/Layout/Sidebar';
import { setting } from '../components/Layout/data';


const settings = () => {
	return (
		<>
			<Head>
				<title>PickBazar</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<div
				style={{height: 'calc(100vh - 92px)'}}
				className='flex items-center w-full'>
				<Sidebar />
				<div
					style={{width: 'calc(100% - 270px)'}}
					className='h-full flex bg-[#f7f7f7]'>
					<div className='py-[45px] px-[30px] h-auto w-full overflow-y-auto'>
						<div className='grid grid-cols-2  gap-5 px-[16px]'>
							{setting.map((item, index) => (
								<div className='py-[35px] px-[20px] cursor-pointer bg-white flex h-full'>
									<div className='mr-[10px text-[#00c58d]  w-[100px] flex items-center justify-center'>{item.icon}</div>
									<div className='flex flex-col'>
										<h3 className='mt-0 m-0 mb-[5px] text-[#00c58d] font-bold leading-6 text-[24px]'>{item.header}</h3>
										<span className='font-normal m-0 leading-6 text-[#161f6a] text-[14px]'>{item.text}</span>
									</div>
								</div>
							))}
						</div>
					</div>
				</div>
			</div>
		</>
	);
};

export default settings;
